apiVersion: v1
kind: Service
metadata:
  name: trading-platform-service
  namespace: trading-platform
  labels:
    app: trading-platform
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: trading-platform
