"use client";

import { useState, useEffect } from "react";
import WatchlistSidebar from "./WatchlistSidebar";
import SignalFeed from "./SignalFeed";
import HeadlessFinancialAnalyst from "./HeadlessFinancialAnalyst";
import RebalancerCard from "./RebalancerCard";
import WelcomeAvatar from "./WelcomeAvatar";

export default function PortfolioDashboard() {
  // Global persistent portfolio state: Ticker -> Weight
  const [portfolio, setPortfolio] = useState<Record<string, number>>({});
  const [selectedTicker, setSelectedTicker] = useState<string | null>(null);
  const [isLoaded, setIsLoaded] = useState(false);

  // Load from local storage on mount
  useEffect(() => {
    const saved = localStorage.getItem("ai_financial_portfolio");
    if (saved) {
      try {
        setPortfolio(JSON.parse(saved));
      } catch (e) {
        console.error("Failed to parse portfolio", e);
      }
    } else {
      // Default initial portfolio
      setPortfolio({
        "AAPL": 0.4,
        "TSLA": 0.3,
        "NVDA": 0.3
      });
    }
    setIsLoaded(true);
  }, []);

  // Save to local storage on change
  useEffect(() => {
    if (isLoaded) {
      localStorage.setItem("ai_financial_portfolio", JSON.stringify(portfolio));
    }
  }, [portfolio, isLoaded]);

  if (!isLoaded) return null;

  return (
    <div className="min-h-screen pt-[68px] bg-[#050505] text-[var(--text-primary)] flex flex-col">
      {/* Top Marquee: Live AI Signals */}
      <div className="shrink-0 h-14 w-full">
        <SignalFeed />
      </div>

      <div className="flex-1 w-full max-w-[1600px] mx-auto p-4 md:p-6 lg:p-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full">
          
          {/* Main Content Area (3/4 on Desktop, full on Mobile) */}
          <div className="lg:col-span-9 flex flex-col gap-8 order-1 lg:order-2">
            
            {/* 1. Selected Asset Deep Dive */}
            <div id="deep-dive" className="bg-[var(--surface-1)] border border-[rgba(255,255,255,0.06)] rounded-md p-6">
              <div className="mb-6 border-b border-[rgba(255,255,255,0.06)] pb-4">
                 <h2 className="font-display text-2xl tracking-wide">
                   Asset Deep Dive
                 </h2>
                 <p className="font-body text-sm text-[var(--text-tertiary)] mt-1">
                   {selectedTicker 
                     ? `Run full multi-agent analysis on ${selectedTicker}.`
                     : "Search for a ticker below, or select one from your watchlist."}
                 </p>
              </div>
              
              <HeadlessFinancialAnalyst initialTicker={selectedTicker || ""} />
            </div>

            {/* 2. Portfolio Rebalancer */}
            <div id="rebalancer" className="bg-[var(--surface-1)] border border-[rgba(255,255,255,0.06)] rounded-md p-6">
              <RebalancerCard 
                portfolio={portfolio}
                setPortfolio={setPortfolio}
              />
            </div>
            
            {/* Legal Disclaimer Footer */}
            <div className="mt-8 pt-6 border-t border-[rgba(255,255,255,0.06)] text-center pb-8">
              <p className="font-mono text-xs text-[var(--text-tertiary)] leading-relaxed max-w-4xl mx-auto">
                Disclaimer: AI Financial Analyst is an educational and informational tool. All insights, data analytics, and agent rebalancing outputs are generated by automated models and do not constitute formal investment or financial advice. Past performance is not indicative of future results.
              </p>
            </div>
          </div>

          {/* Watchlist Sidebar (1/4 on Desktop, drops to bottom on Mobile) */}
          <div className="lg:col-span-3 order-2 lg:order-1">
            <div className="sticky top-24 bg-[var(--surface-1)] border border-[rgba(255,255,255,0.06)] rounded-md overflow-hidden h-[600px] max-h-[calc(100vh-120px)] shadow-xl">
              <WatchlistSidebar 
                portfolio={portfolio} 
                setPortfolio={setPortfolio} 
                onSelectTicker={setSelectedTicker} 
              />
            </div>
          </div>
          
        </div>
      </div>
      
      {/* Voice Assistant Avatar - Scoped to Dashboard Only */}
      <WelcomeAvatar />
    </div>
  );
}
