"use client";

import React, { useMemo } from "react";
import { motion } from "framer-motion";
import { AlertTriangle, TrendingUp, TrendingDown, Activity, Info, ShieldAlert } from "lucide-react";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface StructuredReportProps {
  markdown: string;
}

export default function StructuredReport({ markdown }: StructuredReportProps) {
  const hasApiError = markdown && (markdown.includes("Error code: 429") || markdown.includes("Error code: 400"));

  if (hasApiError) {
    return (
      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full p-6 rounded-md bg-red-950/20 border border-red-900/50 flex items-start gap-4"
      >
        <div className="mt-0.5 text-red-500">
          <AlertTriangle size={24} />
        </div>
        <div>
          <h3 className="font-display text-xl text-red-400 mb-1">API Overloaded</h3>
          <p className="font-body text-sm text-[var(--text-secondary)] leading-relaxed">
            Please wait a moment and try again.
          </p>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6 }}
      className="w-full bg-[var(--surface-1)] border border-[rgba(255,255,255,0.06)] rounded-md p-6 sm:p-8 shadow-2xl"
    >
      <ReactMarkdown 
        remarkPlugins={[remarkGfm]}
        components={{
          h3: ({node, ...props}) => (
            <h3 className="text-xl font-display text-[var(--text-primary)] mt-10 mb-4 border-b border-slate-800 pb-2 flex items-center gap-2" {...props} />
          ),
          h4: ({node, ...props}) => <h4 className="text-lg font-bold text-slate-200 mt-6 mb-2" {...props} />,
          p: ({node, ...props}) => <p className="font-body text-sm text-[var(--text-secondary)] leading-relaxed mb-4" {...props} />,
          ul: ({node, ...props}) => <ul className="space-y-2 pl-4 list-disc mb-6 text-[var(--text-secondary)] font-body text-sm marker:text-[#C8FF00]" {...props} />,
          ol: ({node, ...props}) => <ol className="space-y-2 pl-4 list-decimal mb-6 text-[var(--text-secondary)] font-body text-sm" {...props} />,
          li: ({node, ...props}) => <li className="pl-1" {...props} />,
          table: ({node, ...props}) => (
            <div className="overflow-x-auto mb-8 rounded border border-[rgba(255,255,255,0.06)]">
              <table className="w-full text-left text-sm text-slate-300 table-auto border-collapse" {...props} />
            </div>
          ),
          thead: ({node, ...props}) => <thead className="bg-slate-900/80" {...props} />,
          tbody: ({node, ...props}) => <tbody className="bg-slate-900/20" {...props} />,
          tr: ({node, ...props}) => <tr className="border-b border-slate-800/50 hover:bg-slate-800/40 transition-colors" {...props} />,
          th: ({node, ...props}) => <th className="py-3 px-4 font-mono text-[0.6rem] uppercase tracking-widest text-[var(--text-tertiary)] border-b border-slate-800" {...props} />,
          td: ({node, ...props}) => <td className="py-3 px-4 font-body text-[0.85rem] text-[var(--text-secondary)]" {...props} />,
          strong: ({node, ...props}) => <strong className="font-semibold text-white" {...props} />,
          em: ({node, ...props}) => <em className="italic text-slate-400" {...props} />,
          hr: ({node, ...props}) => <hr className="border-t border-slate-800 my-8" {...props} />,
          blockquote: ({node, ...props}) => (
            <blockquote className="border-l-4 border-[#C8FF00] pl-4 my-4 italic text-slate-400 bg-slate-900/30 py-2 pr-4 rounded-r" {...props} />
          )
        }}
      >
        {markdown || "No data available."}
      </ReactMarkdown>
      
      {/* Footer Meta */}
      <div className="text-center pt-8 mt-4 border-t border-[rgba(255,255,255,0.06)]">
         <p className="font-mono text-[0.55rem] text-[var(--text-tertiary)] uppercase tracking-widest">
            Generated by AI Financial Analyst · Multi-Agent Data Aggregation
         </p>
      </div>
    </motion.div>
  );
}
