"use client";

import { motion } from "framer-motion";
import { useRouter } from "next/navigation";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: [
      "By accessing and using anishreddy.online, including live AI model inference demos and research showcases, you agree to be bound by these Terms of Service.",
      "If you do not agree to these terms, please do not access or use our site and hosted endpoints.",
    ],
  },
  {
    title: "2. Platform & System Overview",
    content: [
      "This website serves as a personal AI research and engineering portfolio showcasing multi-agent systems, deep learning computer vision models (EfficientNet-B0, Custom CNNs), Grad-CAM explainability, and real-time FastAPI production pipelines.",
      "All features, demos, and model endpoints are provided free of charge for research, educational, and technical evaluation purposes. No paid services or commercial transactions exist on this platform.",
    ],
  },
  {
    title: "3. Acceptable Use of AI Models & APIs",
    content: [
      "Educational & Evaluation Use: You may use interactive model demos (Plant Disease Detection, Skin Cancer Inference, Financial Analyst Agents) solely for personal, research, or evaluation purposes.",
      "No Malicious Payloads: You agree not to submit malicious code, corrupt media files, or automated rate-limit bypass scripts to our hosted Hugging Face Spaces or Render endpoints.",
      "Demonstration Disclaimer: Machine learning outputs (including plant disease predictions, skin cancer classifications, and financial return forecasts) are generated by automated probabilistic models. They are for technical demonstration only and DO NOT constitute medical, financial, investment, or legal advice.",
    ],
  },
  {
    title: "4. Intellectual Property & Open Source",
    content: [
      "All proprietary code, custom neural architectures, UI designs, and technical writeups on this site are the intellectual property of Anish Reddy unless designated under explicit open-source licenses (e.g. Apache 2.0 / MIT).",
      "Third-party libraries, datasets (e.g. HAM10000, PlantVillage, SEC EDGAR), and frameworks belong to their respective owners.",
    ],
  },
  {
    title: "5. Disclaimer of Warranties",
    content: [
      "This website and its associated ML model endpoints are provided 'AS IS' and 'AS AVAILABLE' without warranties of any kind, express or implied.",
      "We do not guarantee 100% uptime, zero latency, or complete accuracy of machine learning predictions.",
    ],
  },
  {
    title: "6. Limitation of Liability",
    content: [
      "Anish Reddy shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of or reliance on machine learning outputs, model predictions, or website content.",
    ],
  },
  {
    title: "7. Contact & Inquiries",
    content: [
      "For questions regarding these Terms of Service or model licensing, please reach out to Anish Reddy at anishreddy1373@gmail.com.",
    ],
  },
];

export default function TermsPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen" style={{ background: "var(--surface-0)" }}>

      {/* Top accent */}
      <div className="h-px w-full"
        style={{ background: "linear-gradient(90deg, transparent, #FF2D2D, #FF6B35, transparent)" }} />

      {/* Header */}
      <div className="sticky top-0 z-50 px-4 sm:px-8 py-4 flex items-center justify-between"
        style={{ background: "rgba(10, 10, 10, 0.92)", backdropFilter: "blur(20px)", borderBottom: "1px solid rgba(255,45,45,0.12)" }}>
        <button onClick={() => router.push("/")}
          className="font-display text-lg tracking-[0.15em]"
          style={{ color: "var(--text-primary)" }}>
          ANISHREDDY<span style={{ color: "#FF2D2D" }}>.</span>ONLINE
        </button>
        <button onClick={() => router.back()}
          className="font-mono text-[0.6rem] tracking-widest uppercase"
          style={{ color: "var(--text-tertiary)" }}
          onMouseEnter={(e) => ((e.target as HTMLElement).style.color = "var(--text-primary)")}
          onMouseLeave={(e) => ((e.target as HTMLElement).style.color = "var(--text-tertiary)")}>
          ← Back
        </button>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-8 py-16">

        {/* Title */}
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="mb-12">
          <p className="font-mono text-[0.58rem] tracking-[0.32em] uppercase mb-4"
            style={{ color: "#FF2D2D" }}>Legal & Systems Terms</p>
          <h1 className="font-display text-4xl sm:text-5xl tracking-[0.1em] mb-4"
            style={{ color: "var(--text-primary)" }}>
            Terms of Service
          </h1>
          <p className="font-mono text-[0.6rem] tracking-widest" style={{ color: "var(--text-tertiary)" }}>
            Last updated: July 2026 · Anish Reddy (AI Researcher)
          </p>
          <div className="mt-6 h-px w-16"
            style={{ background: "linear-gradient(90deg, #FF2D2D, transparent)" }} />
        </motion.div>

        {/* Intro */}
        <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.1 }}
          className="font-body text-sm leading-relaxed mb-12"
          style={{ color: "var(--text-secondary)" }}>
          These Terms of Service govern your use of the AnishReddy.Online portfolio website, live AI model inference endpoints, multi-agent systems, and technical research showcases.
        </motion.p>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((section, i) => (
            <motion.div key={section.title}
              initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 + i * 0.05 }}
              className="rounded-sm p-6"
              style={{ background: "var(--surface-1)", border: "1px solid rgba(255,255,255,0.06)" }}>
              <h2 className="font-mono text-[0.6rem] tracking-[0.28em] uppercase mb-4"
                style={{ color: "#FF2D2D" }}>{section.title}</h2>
              <ul className="space-y-3">
                {section.content.map((item, j) => (
                  <li key={j} className="flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full mt-2 shrink-0"
                      style={{ background: "#FF2D2D" }} />
                    <p className="font-body text-sm leading-relaxed"
                      style={{ color: "var(--text-secondary)" }}>{item}</p>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

        {/* Footer note */}
        <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
          className="font-mono text-[0.55rem] tracking-widest uppercase mt-12 text-center"
          style={{ color: "var(--text-tertiary)" }}>
          © {new Date().getFullYear()} AnishReddy.Online — AI Researcher & Engineer
        </motion.p>
      </div>
    </div>
  );
}